---
title: "Jordan_Final"
author: "Hannah Jordan"
date: '2022-05-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#' Final Package
#'
#' @param x 
#' @param y 
#' @param alpha 
#'
#' @return
#' @export
#'
#' @examples
#' 

library(kableExtra)
library(FinalProject)
library(magrittr)

myttest = function(x, y, alpha){
  Rttest2 <- t.test(x, y, mu = 0, var.equal = TRUE, conf.level = 1-alpha)
  obj <- list(data = data.frame(x=x, y=y), Confidence_Interval = Rttest2$conf.int, P.value = Rttest2$p.value, Alpha = alpha)
  class(obj) <- "Rttest"
  Rttest
}

#Print Function
#' Title
#'
#' @param x 
#' @param ... 
#'
#' @return
#' @export
#'
#' @examples
print.Rttest <- function(x,...) {
  data = c(Rttest$data,Rttest$Confidence_Interval,Rttest$P.value,Rttest$Alpha)
  #Rttest$data = x[["data"]][["x"]], x[["data"]][["y"]]
  #Rttest$Alpha = alpha[["Alpha"]]
  #dataframe = data.frame(Rttest$data, Rttest$Alpha) 
 
  #kable(dataframe)
 
  kable_styling(kableExtra::kable(data,align = "c", col.names = names(data())))
 
}

plot.Rttest = function(x, y, pch =21, bg = "blue", cex = 3){
    plot(data,
         pch = pch,
         bg = bg,
         x = "x",
         y = "y"
    )
}

#firstcall
#quartz(); boxplot(Rttest$data)

#CHECK FUNCTION
#check()
#THIS GOES IN MESSAGES

#Plot Function

#data
set.seed(32); x=rnorm(30,mean=10,sd=15)
set.seed(35); y=rnorm(30,mean=8,sd=15)

alpha <- 0.05
Cat <- rep(c("A", "B"), c(30,30))
data.frame(MeanValue = c(x,y), TheData = Cat) -> data
library(ggplot2)
TheData <- ggplot(data) + geom_boxplot(aes(x = TheData, y = MeanValue, fill = TheData))
TheData






#ActualData

ans1=FinalProject::myttest(x,y,alpha=0.05,paired=FALSE)
library(FinalProject)
print(ans1)
plot(ans1)


ans2=FinalProject::myttest(x,y,alpha=0.05,paired=FALSE)
print(ans2)
plot(ans2)


ans3=FinalProject::myttest(x,y,alpha=0.05,paired=TRUE)
print(ans3)
plot(ans3)

#class(Rttest)

```

